wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.5
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713146231.0
    t:
      1:
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.16.5
      8:
      - 1
      - 5
      13: darwin-arm64
